export const teamMembers = [
  {
    id: 1,
    name: 'Nguyễn Thị Diệu',
    role: 'Project Manager',
    email: 'dieupvn345@gmail.com',
    phone: '0123 456 789',
    github: 'https://github.com/dieupvn',
    linkedin: 'https://linkedin.com/in/dieupvn',
    instagram: 'https://instagram.com/dieupvn',
    skills: ['github', 'trello'],
    color: 'rgb(46, 239, 171)',
    avatar: require('../assets/images/Dieu.jpg'),
  },
  {
    id: 2,
    name: 'Đỗ Lâm Trang',
    role: 'Frontend Developer',
    email: 'tranglam17115@gmail.com',
    phone: '0987 654 321',
    github: 'https://github.com/dieupvn',
    linkedin: 'https://linkedin.com/in/dieupvn',
    instagram: 'https://instagram.com/dieupvn',
    skills: ['html5', 'css3', 'react'],
    color: 'rgb(248, 114, 208)',
    avatar: require('../assets/images/Nhi.jpg'),
  },
  {
    id: 3,
    name: 'Nguyễn Dương Sâm',
    role: 'Backend Developer',
    email: 'duonghoangsamet@gmail.com',
    phone: '0912 345 678',
    github: 'https://github.com/dieupvn',
    linkedin: 'https://linkedin.com/in/dieupvn',
    instagram: 'https://instagram.com/dieupvn',
    skills: ['github', 'node-js', 'java', 'python', 'database'],
    color: 'rgb(68, 164, 242)',
    avatar: require('../assets/images/Sam.jpg'),
  },
  {
    id: 4,
    name: 'Lê Hải Bắc',
    role: 'Mobile Developer',
    email: 'lehbac05@gmail.com',
    phone: '0901 234 567',
    github: 'https://github.com/dieupvn',
    linkedin: 'https://linkedin.com/in/dieupvn',
    instagram: 'https://instagram.com/dieupvn',
    skills: ['react', 'android', 'react-native'],
    color: 'rgb(240, 34, 34)',
    avatar: require('../assets/images/Bac.jpg'),
  },
  {
    id: 5,
    name: 'Nguyễn Hồng Ngọc',
    role: 'Tester',
    email: 'nguyenngocanh2005a@gmail.com',
    phone: '0933 888 999',
    github: 'https://github.com/dieupvn',
    linkedin: 'https://linkedin.com/in/dieupvn',
    instagram: 'https://instagram.com/dieupvn',
    skills: ['bug', 'jira', 'selenium'],
    color: 'rgb(253, 185, 58)',
    avatar: require('../assets/images/Ngoc.png'),
  },
];