import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    container: {
        padding: 16,
        backgroundColor: '#f8f9fa', 
    },
    title: {
        fontSize: 22,
        fontWeight: "bold",
        textAlign: "center",
        color: "#FF6B35", 
        marginBottom: 20,
    },
    cardContainer: {
        flexDirection: "row",
        justifyContent: "space-between",
        marginBottom: 25,
    },
    productCard: {
        width: "30%",
        alignItems: "center",
        borderRadius: 16, 
        padding: 12, 
        backgroundColor: '#ffffff', 
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.15,
        elevation: 5, 
        borderWidth: 1,
        borderColor: '#e9ecef',
    },
    platformBadge: {
        backgroundColor: "#FF6B35", 
        color: "#fff",
        fontWeight: "bold",
        paddingVertical: 6, 
        paddingHorizontal: 12, 
        borderRadius: 14, 
        fontSize: 12,
        marginBottom: 10, 
    },
    productImage: {
        width: 80, 
        height: 80, 
        resizeMode: "contain",
        borderRadius: 8, 
        marginBottom: 8, 
    },
    platformLogo: {
        width: 18, 
        height: 16,
        resizeMode: "contain", 
        marginVertical: 0,
    },
    price: {
        color: "#FF6B35", 
        fontWeight: "bold",
        fontSize: 12, 
        marginBottom: 8, 
        textAlign: 'center', 
        lineHeight: 16, 
        flexWrap: 'nowrap', 
    },
    buyButton: {
        marginTop: 10, 
        backgroundColor: "#FF6B35", 
        borderRadius: 10, 
        paddingVertical: 8,
        paddingHorizontal: 12, 
        shadowColor: "#FF6B35",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        elevation: 3,
        alignItems: 'center', 
        justifyContent: 'center', 
    },
    buyButtonText: {
        color: "#fff",
        fontSize: 12, 
        fontWeight: "bold",
        textAlign: 'center', 
        lineHeight: 14, 
    },
    sectionTitle: {
        fontSize: 18,
        fontWeight: "bold",
        marginBottom: 14,
        color: "#FF6B35", 
    },
    table: {
        backgroundColor: "#ffffff", 
        borderRadius: 12, 
        borderWidth: 1,
        borderColor: "#e9ecef", 
        overflow: "hidden",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.15,
        shadowRadius: 4, 
        elevation: 3, 
    },
    tableHeader: {
        backgroundColor: "#f8f9fa",
        borderBottomWidth: 1,
        borderBottomColor: "#e9ecef",
    },
    tableRow: {
        flexDirection: "row",
        borderBottomWidth: 0.5,
        borderColor: "#f1f3f4", 
        paddingVertical: 14, 
        alignItems: "center",
    },
    labelCell: {
        flex: 1.6,
        fontWeight: "600",
        paddingHorizontal: 14, 
        fontSize: 13,
        color: "#6c757d",
        textAlign: 'left',
    },
    valueCell: {
        flex: 1,
        textAlign: "center",
        fontSize: 10,
        color: "#6c757d",
        fontWeight: "500", 
        lineHeight: 16,
    },
    valueCellHeader: {
        flex: 1,
        textAlign: "center",
        fontSize: 13,
        fontWeight: "bold",
        color: "#FF6B35", // Header thay đổi từ đỏ sang cam
        lineHeight: 16, // Đặt line height để text đều
    },
    backButton: {
        marginTop: 20,
        marginBottom: 40,
        padding: 14, 
        backgroundColor: "#FF6B35", 
        borderRadius: 10, 
        alignItems: "center",
        shadowColor: "#FF6B35",
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.2, 
        shadowRadius: 4, 
        elevation: 4, 
    },
    backButtonText: {
        color: "#fff",
        fontSize: 16,
        fontWeight: "bold",
    },
})